name: Conventional Commits PR Title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title for Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          scopes: |
            app
            tauri
            ci
            release
            deps
          requireScope: false
          subjectPattern: ^(?![A-Z]).+
          subjectPatternError: Subject must start with a lowercase letter
          wip: true
